Repository mesosphere/kubeaddons-kommander, pull requests merged in 2020-08, with the labels that each got.

#133 [stable-1.1.x] Bump chart to 0.8.43
  addons/kommander/1.1.1/kommander-1.yaml
Labels: ready

#136 [chore] Update dependencies and fix CI
  test/go.mod
  test/go.sum
  test/karma_test.go
  test/kommander_test.go
  test/kubecost_test.go
  test/setup_test.go
  test/thanos_test.go
  test/unhandled_addons_test.go
  test/vars_test.go
Labels: chore, ready

#138 chore: Update mergebot-config
  mergebot-config.json
Labels: ready

#137 Merge stable-1.1.x back into master
  addons/kommander/1.1.1/kommander-1.yaml
Labels: ready

#132 chore: Bump chart to 0.9.4
  addons/kommander/1.2.0/kommander-3.yaml
Labels: ready

#140 kommander release via helm3
  addons/kommander/1.2.0/kommander-4.yaml
  test/kommander_test.go
  test/vars_test.go
Labels: ready

#141 [stable-1.1.x] Bump chart version to 0.8.44
  addons/kommander/1.1.2/kommander-1.yaml
  addons/kommander/1.2.0/kommander-1.yaml
Labels: ready

#142 chore: bump kommander
  addons/kommander/1.2.0/kommander-5.yaml
Labels: blocked, issues in ci

#146 chore: Update mergebot-config
  mergebot-config.json
Labels: ready

#145 Merge stable-1.1.x to master
  addons/kommander/1.1.2/kommander-1.yaml
Labels: ready
