Repository mesosphere/kubeaddons-kommander, pull requests merged in 2020-04, with the labels that each got.

#55 chore: bump chart 0.6.4 -> 0.6.7
  addons/kommander/1.1.x/kommander.yaml
Labels: ready

#58 chore: bump kcl version
  addons/kommander/1.1.x/kommander.yaml
Labels: wip

#53 [to be merged 2020-04-22] Update Stable and Release "Kommander 1.1.0 Beta 1"
  addons/kommander/1.1.x/kommander.yaml
Labels: blocked, ready

#57 [to be merged 2020-04-23] update soak with what will be 1.1.0 beta 2
  addons/kommander/1.1.x/kommander.yaml
Labels: blocked, ready

#59 chore: bump kcl
  addons/kommander/1.1.x/kommander.yaml
Labels: ready

#60 chore: bump kommander chart version to 0.6.12
  addons/kommander/1.1.x/kommander.yaml
Labels: ready

#63 chore: bump kcl
  addons/kommander/1.1.x/kommander.yaml
Labels: ready
