Repository mesosphere/kubeaddons-kommander, pull requests merged in 2020-09, with the labels that each got.

#148 chore: manual bot bumping kommander
  addons/kommander/1.2.0/kommander-6.yaml
Labels: ready

#150 chore: manual bot v2 bumping kommander
  addons/kommander/1.2.0/kommander-8.yaml
Labels: ready

#151 chore: manual bump of kommander
  addons/kommander/1.2.0/kommander-9.yaml
  test/bundle.yaml
  test/vars_test.go
Labels: issues in ci, wip

#153 [D2IQ-71705] Update Kubeaddons in CI
  test/bundle.yaml
  test/vars_test.go
Labels: chore, ready

#154 [D2IQ-71741] Update for v1.19x k8s libs and kubeaddons v0.20.x
  test/go.mod
  test/go.sum
  test/kommander_test.go
Labels: chore, ready

#124 Improve release docs
  README.md
Labels: needs-followup, wip

#155 [D2IQ-71747] Add default upgrade testing to CI
  test/go.mod
  test/go.sum
  test/kommander_test.go
Labels: ci, enhancement, ready

#162 Automated chart bump kommander-0.11.6
  addons/kommander/1.2/kommander.yaml
  test/artifacts/kubecost-checker.yaml
Labels: ready

#161 chore: [vsphere] enabled kommander for new provider
  addons/kommander/1.2/kommander.yaml
Labels: ready

#168 [D2IQ-72015] Fix storage race condition for Kommander addon
  addons/kommander/1.2/kommander.yaml
Labels: bug, ready

#171 Use the default upgrade strategy for Kommander
  addons/kommander/1.2/kommander.yaml
Labels: bug, chore, ready
