Repository mesosphere/kubeaddons-kommander, pull requests merged in 2020-05, with the labels that each got.

#64 remove k8s version override from ui
  addons/kommander/1.1.x/kommander.yaml
Labels: ready

#62 [1.0.x] Kommander 1.0.1 bits n pieces
  addons/kommander/1.0.x/kommander.yaml
Labels: wip

#67 chore: Bump kommander chart version
  addons/kommander/1.1.x/kommander.yaml
Labels: ready

#61 document current release steps and add step by step guides
  README.md
Labels: ready

#70 chore: bump KCL to v0.6.20
  addons/kommander/1.1.x/kommander.yaml
Labels: ready

#71 chore: bump kommander chart to from 0.6.20 to 0.7.1
  addons/kommander/1.1.x/kommander.yaml
Labels: chore, ready

#74 test: Add kubecost e2e tests
  test/artifacts/kubecost-checker.yaml
  test/kommander_test.go
  test/kubecost_test.go
Labels: ready

#77 chore: bump kommander chart version to 0.8.1
  addons/kommander/1.1.x/kommander.yaml
Labels: ready

#79 chore: bump Kommander addon
  addons/kommander/1.1.x/kommander.yaml
Labels: ready

#80 chore: Bump kommmander chart to 0.8.2, add kubecost label
  addons/kommander/1.1.x/kommander.yaml
Labels: ready
