Repository mesosphere/kubeaddons-kommander, pull requests merged in 2020-03, with the labels that each got.

#33 [chore] use logging hook for test.Cluster
  test/addons_test.go
  test/go.mod
  test/go.sum
Labels: enhancement, ready

#32 [chore] use new test.Groups
  test/addons_test.go
  test/scripts/test-wrapper.go
Labels: chore, enhancement, ready

#31 [chore] remove old controller deployment hack
  test/addons_test.go
Labels: chore, ready

#37 Update CODEOWNERS
  CODEOWNERS
Labels: ready

#39 fix: bump kommander to 0.5.1 (#35)
  addons/kommander/1.0.x/kommander.yaml
Labels: ready

#38 [feature] Kommander Thanos API Test
  test/addons_test.go
  test/artifacts/thanos-checker.yaml
  test/go.mod
  test/go.sum
  test/kommander_test.go
  test/setup_test.go
  test/thanos_test.go
  test/unhandled_addons_test.go
  test/utils_test.go
  test/vars_test.go
Labels: enhancement, ready

#43 fix: fix ingress & bumps Kommander ui from 3.6.1 to 3.12.3
  addons/kommander/1.1.x/kommander.yaml
Labels: ready

#44 [D2IQ-65338] add kommander karma api tests
  test/go.mod
  test/go.sum
  test/karma_test.go
  test/kommander_test.go
Labels: ready

#45 [chore] move to new test framework upstream
  test/go.mod
  test/go.sum
  test/karma_test.go
  test/kommander_test.go
  test/scripts/test-wrapper.go
  test/setup_test.go
  test/thanos_test.go
Labels: chore, ready

#47 chore: bump kommander chart reference 0.5.2 -> 0.5.7
  addons/kommander/1.1.x/kommander.yaml
Labels: ready
