Repository mesosphere/kubeaddons-kommander, pull requests merged in 2020-06, with the labels that each got.

#85 chore: bump yakcl chart and disable provisioning module
  addons/kommander/1.1.x/kommander.yaml
Labels: ready

#84 Update Kommander AppVersion to RC 2
  addons/kommander/1.1.x/kommander.yaml
Labels: ready

#86 feat: only expose K8s version >=1.16.0 from utility API server
  addons/kommander/1.1.x/kommander.yaml
Labels: enhancement, ready

#88 Update Karma/Thanos versions in Metadata
  addons/kommander/1.1.x/kommander.yaml
Labels: ready

#91 chore: Bump kommander to 0.8.12
  addons/kommander/1.1.x/kommander.yaml
Labels: ready

#94 chore: Bump chart
  addons/kommander/1.1.x/kommander.yaml
Labels: ready

#96 chore: bump kommander chart
  addons/kommander/1.1.x/kommander.yaml
Labels: ready

#100 fix: Add reloader annotation to thanos query deployment
  addons/kommander/1.1.x/kommander.yaml
Labels: ready

#98 re-add old revisions
  addons/kommander/1.0.0/kommander-1.yaml
  addons/kommander/1.0.0/kommander-10.yaml
  addons/kommander/1.0.0/kommander-13.yaml
  addons/kommander/1.0.0/kommander-14.yaml
  addons/kommander/1.0.0/kommander-15.yaml
  addons/kommander/1.0.0/kommander-16.yaml
  addons/kommander/1.0.0/kommander-17.yaml
  addons/kommander/1.0.0/kommander-18.yaml
  addons/kommander/1.0.0/kommander-19.yaml
  addons/kommander/1.0.0/kommander-2.yaml
  addons/kommander/1.0.0/kommander-20.yaml
  addons/kommander/1.0.0/kommander-3.yaml
  addons/kommander/1.0.0/kommander-4.yaml
  addons/kommander/1.0.0/kommander-5.yaml
  addons/kommander/1.0.0/kommander-6.yaml
  addons/kommander/1.0.0/kommander-7.yaml
  addons/kommander/1.0.0/kommander-8.yaml
  addons/kommander/1.0.0/kommander-9.yaml
  addons/kommander/1.0.1/kommander-1.yaml
  addons/kommander/1.1.0/kommander-1.yaml
  addons/kommander/1.1.0/kommander-10.yaml
  addons/kommander/1.1.0/kommander-11.yaml
  addons/kommander/1.1.0/kommander-12.yaml
  addons/kommander/1.1.0/kommander-13.yaml
  addons/kommander/1.1.0/kommander-14.yaml
  addons/kommander/1.1.0/kommander-15.yaml
  addons/kommander/1.1.0/kommander-16.yaml
  addons/kommander/1.1.0/kommander-17.yaml
  addons/kommander/1.1.0/kommander-18.yaml
  addons/kommander/1.1.0/kommander-19.yaml
  addons/kommander/1.1.0/kommander-2.yaml
  addons/kommander/1.1.0/kommander-20.yaml
  addons/kommander/1.1.0/kommander-21.yaml
  addons/kommander/1.1.0/kommander-22.yaml
  addons/kommander/1.1.0/kommander-23.yaml
  addons/kommander/1.1.0/kommander-24.yaml
  addons/kommander/1.1.0/kommander-25.yaml
  addons/kommander/1.1.0/kommander-26.yaml
  addons/kommander/1.1.0/kommander-27.yaml
  addons/kommander/1.1.0/kommander-28.yaml
  addons/kommander/1.1.0/kommander-29.yaml
  addons/kommander/1.1.0/kommander-3.yaml
  addons/kommander/1.1.0/kommander-30.yaml
  addons/kommander/1.1.0/kommander-31.yaml
  addons/kommander/1.1.0/kommander-32.yaml
  addons/kommander/1.1.0/kommander-33.yaml
  addons/kommander/1.1.0/kommander-34.yaml
  addons/kommander/1.1.0/kommander-35.yaml
  addons/kommander/1.1.0/kommander-36.yaml
  addons/kommander/1.1.0/kommander-37.yaml
  addons/kommander/1.1.0/kommander-38.yaml
  addons/kommander/1.1.0/kommander-39.yaml
  addons/kommander/1.1.0/kommander-4.yaml
  addons/kommander/1.1.0/kommander-5.yaml
  addons/kommander/1.1.0/kommander-6.yaml
  addons/kommander/1.1.0/kommander-7.yaml
  addons/kommander/1.1.0/kommander-8.yaml
  addons/kommander/1.1.0/kommander-9.yaml
Labels: ready

#101 chore: bumps kommander chart
  addons/kommander/1.1.0/kommander-40.yaml
Labels: chore, ready

#105 chore: set allowUnofficialReleases to false
  addons/kommander/1.1.0/komander-44.yaml
Labels: ready

#106 Bump kommander to 0.8.29
  addons/kommander/1.1.0/kommander-44.yaml
Labels: ready

#107 Bump Kommander to 0.8.31
  addons/kommander/1.1.0/kommander-45.yaml
Labels: ready

#109 Bump Kommander to 0.8.32
  addons/kommander/1.1.0/kommander-46.yaml
Labels: ready

#108 chore: Reapply #105 (set allowUnofficialReleases to false)
  addons/kommander/1.1.0/kommander-47.yaml
Labels: ready
